# Generated by Django 5.2.13 on 2026-08-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='face_descriptor',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
