# Generated by Django 5.2.13 on 2026-08-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('BOOKING', 'Booking'), ('MESSAGE', 'Message'), ('SESSION_REMINDER', 'Session reminder'), ('ANNOUNCEMENT', 'Announcement')], max_length=20),
        ),
    ]
