# Generated by Django 5.2.13 on 2026-08-25 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_member_face_descriptor'),
        ('plans', '0009_alter_workoutday_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('WORKOUT', 'برنامه تمرینی'), ('WALK', 'پیاده\u200cروی'), ('RUN', 'دویدن')], max_length=10)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('calories_burned', models.PositiveIntegerField()),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='accounts.member')),
                ('workout_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='plans.workoutplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
