# Generated by Django 5.2.13 on 2026-09-01 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('plans', '0009_alter_workoutday_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='workout_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='plans.workoutday'),
        ),
    ]
