# Generated by Django 5.2.13 on 2026-08-24 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_membershipplan_organization_and_more'),
        ('organizations', '0002_backfill_default_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_plans', to='organizations.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='membershipplan',
            unique_together={('organization', 'name')},
        ),
    ]
