# Generated by Django 5.2.13 on 2026-08-25 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_member_face_descriptor'),
        ('memberships', '0003_alter_membershipplan_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(help_text='1, 2 or 3 — leaderboard position at grant time.')),
                ('percent', models.PositiveIntegerField(help_text='Discount percentage applied to the next plan purchase.')),
                ('is_redeemed', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_rewards', to='accounts.member')),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
    ]
