# Generated by Django 5.2.13 on 2026-09-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_leaderboardreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardreward',
            name='residual_percent',
            field=models.PositiveIntegerField(default=0, help_text='Standing discount kept after the one-time prize is spent.'),
        ),
        migrations.AlterField(
            model_name='leaderboardreward',
            name='percent',
            field=models.PositiveIntegerField(help_text='One-time discount on the next plan purchase.'),
        ),
    ]
