# Generated by Django 5.2.13 on 2026-08-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_dietplan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workout_plans/'),
        ),
    ]
