# Generated by Django 5.2.13 on 2026-08-24 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('plans', '0003_workoutplan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplanitem',
            name='exercise_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='workoutplanitem',
            name='workout_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_items', to='plans.workoutplan'),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('muscle_group', models.CharField(choices=[('CHEST', 'سینه'), ('BACK', 'پشت'), ('LEGS', 'پا'), ('SHOULDERS', 'شانه'), ('ARMS', 'بازو'), ('CORE', 'شکم'), ('CARDIO', 'هوازی'), ('FULL_BODY', 'کل بدن')], default='FULL_BODY', max_length=20)),
                ('video_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='workoutplanitem',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='plans.exercise'),
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='plans.workoutplan')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('workout_plan', 'day_number')},
            },
        ),
        migrations.AddField(
            model_name='workoutplanitem',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plans.workoutday'),
        ),
    ]
