# Generated by Django 5.2.13 on 2026-08-24 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_backfill_workout_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplanitem',
            name='exercise_name',
        ),
        migrations.RemoveField(
            model_name='workoutplanitem',
            name='workout_plan',
        ),
        migrations.AlterField(
            model_name='workoutplanitem',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plans.workoutday'),
        ),
        migrations.AlterField(
            model_name='workoutplanitem',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='plans.exercise'),
        ),
    ]
