# Generated by Django 5.2.13 on 2026-08-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_remove_workoutplanitem_exercise_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutday',
            options={'ordering': ['date']},
        ),
        migrations.AlterUniqueTogether(
            name='workoutday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workoutday',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
