# Generated by Django 5.2.13 on 2026-08-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_backfill_workout_day_dates'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workoutday',
            unique_together={('workout_plan', 'date')},
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='date',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='workoutday',
            name='day_number',
        ),
    ]
