# Generated by Django 5.2.13 on 2026-08-11 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('body_fat_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='accounts.member')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
