# Generated by Django 5.2.13 on 2026-09-01 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_member_show_on_leaderboard_trainer_bio_html_and_more'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_sessions', models.PositiveIntegerField(default=4)),
                ('monthly_sessions', models.PositiveIntegerField(default=12)),
                ('daily_calories', models.PositiveIntegerField(default=400)),
                ('target_weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='accounts.member')),
            ],
        ),
    ]
