# Generated by Django 5.2.13 on 2026-08-24 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gym_classes', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='gymclass',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
