# Generated by Django 5.2.13 on 2026-08-24 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_gymclass_organization_alter_gymclass_name'),
        ('organizations', '0002_backfill_default_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_classes', to='organizations.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='gymclass',
            unique_together={('organization', 'name')},
        ),
    ]
