# Generated by Django 5.2.13 on 2026-08-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_gymclass_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='classes/'),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='description_html',
            field=models.TextField(blank=True),
        ),
    ]
