# Generated by Django 5.2.13 on 2026-08-24 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_member_face_descriptor'),
        ('organizations', '0002_backfill_default_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('INDIVIDUAL', 'فردی'), ('TEAM', 'تیمی')], default='INDIVIDUAL', max_length=10)),
                ('level', models.CharField(choices=[('ALL', 'همه سطوح'), ('BEGINNER', 'مبتدی'), ('INTERMEDIATE', 'متوسط'), ('ADVANCED', 'پیشرفته')], default='ALL', max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='competitions/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='organizations.organization')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competitions.competition')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_entries', to='accounts.member')),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('competition', 'member')},
            },
        ),
        migrations.CreateModel(
            name='CompetitionPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(help_text='1 = اول, 2 = دوم, ...')),
                ('title', models.CharField(max_length=150)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='competitions.competition')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('competition', 'rank')},
            },
        ),
    ]
